### ISSUE TITLE
[BUG] Failed to run metal extension during downloading SemanticDB pom

### ISSUE THREAD

**Issue by takatoyamada** [scalameta/metals-vscode#1002]
I recently encountered the following error when I start to run VSCode, which seems to fail downloading `/semanticdb-scalac_2.13.3-4.5.3.pom`, but I thought to set proxy information properly.
Is there anyone who knows about this phenomenon?

My environment information.
- sbt (1.6.2) and scala (2.13.3)
- metal extension (v1.16.0)
- it always works behind proxy, but I did 
  - set `metals.serverProperties` in my .vscode for workspace
  - locate .jvmopts under the top directory of my workspace
  - set `ENV JAVA_OPTS="-Dhttps.proxyHost={ proxy host IP like 8.8.8.8 } -Dhttps.proxyPort={ proxy port like 8888 }"` in my Dockerfile

```
2022.06.03 11:09:49 WARN  Stopped configuration of Scala SemanticDB in 2.12.15 projects: Error downloading org.scalameta:semanticdb-scalac_2.12.15:4.5.3
  not found: /root/.ivy2/local/org.scalameta/semanticdb-scalac_2.12.15/4.5.3/ivys/ivy.xml
  download error: Caught java.net.UnknownHostException (repo1.maven.org) while downloading https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.15/4.5.3/semanticdb-scalac_2.12.15-4.5.3.pom
2022.06.03 11:09:49 WARN  Stopped configuration of Scala SemanticDB in 2.13.3 projects: Error downloading org.scalameta:semanticdb-scalac_2.13.3:4.5.3
  not found: /root/.ivy2/local/org.scalameta/semanticdb-scalac_2.13.3/4.5.3/ivys/ivy.xml
  download error: Caught java.net.UnknownHostException (repo1.maven.org) while downloading https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.3/4.5.3/semanticdb-scalac_2.13.3-4.5.3.pom
2022.06.03 11:09:49 ERROR Failed to connect with build server, no functionality will work.
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: repo1.maven.org
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at scala.meta.internal.metals.BuildServerConnection$.initialize(BuildServerConnection.scala:437)
	at scala.meta.internal.metals.BuildServerConnection$.$anonfun$fromSockets$1(BuildServerConnection.scala:347)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: repo1.maven.org
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tgodzik** [comment]
Thanks for reporting! The semanticdb is also downloaded by Bloop, which needs to have the proxy settings included in `~/.bloop/bloop.json`. We should improve it to forward the settings automatically.

**Comment by tgodzik** [comment]
Actually with this release we should be able to set `metals.bloopJvmProperties` with the proxies and that should work. Could you try that?
