### ISSUE TITLE
Metals fails on VS Code Dev Container

### ISSUE THREAD

**Issue by hugo-vrijswijk** [scalameta/metals-vscode#103]
Yesterday, [VS Code Remote] was announced. Unfortunately, I ran into some problems getting Dev Container running on a Scala project.

When opening the dev container, right after metals is installed and starts, the following is logged:
```
Java home: /docker-java-home
logging to file /workspaces/stryker4s/.metals/metals.log
[Error - 20:12:43] Server initialization failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.io.FileNotFoundException: /workspaces/stryker4s/.metals/metals.log (No such file or directory)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:21)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:18)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:874)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:872)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /workspaces/stryker4s/.metals/metals.log (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileWriter.<init>(FileWriter.java:107)
	at scribe.writer.file.IOLogFileWriter.writer$lzycompute(IOLogFileWriter.scala:7)
	at scribe.writer.file.IOLogFileWriter.writer(IOLogFileWriter.scala:7)
	at scribe.writer.file.IOLogFileWriter.write(IOLogFileWriter.scala:9)
	at scribe.writer.file.LogFile.write(LogFile.scala:69)
	at scribe.writer.FileWriter.write(FileWriter.scala:27)
	at scribe.handler.SynchronousLogHandler$.$anonfun$log$3(SynchronousLogHandler.scala:26)
	at scribe.handler.SynchronousLogHandler$.$anonfun$log$3$adapted(SynchronousLogHandler.scala:24)
	at scala.Option.foreach(Option.scala:274)
	at scribe.handler.SynchronousLogHandler$.log(SynchronousLogHandler.scala:24)
	at scribe.handler.SynchronousLogHandler.log(SynchronousLogHandler.scala:18)
	at scribe.Logger.$anonfun$log$4(Logger.scala:41)
	at scribe.Logger.$anonfun$log$4$adapted(Logger.scala:41)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scribe.Logger.$anonfun$log$3(Logger.scala:41)
	at scribe.Logger.$anonfun$log$3$adapted(Logger.scala:40)
	at scala.Option.foreach(Option.scala:274)
	at scribe.Logger.log(Logger.scala:40)
	at scribe.Logger.$anonfun$log$6(Logger.scala:42)
	at scribe.Logger.$anonfun$log$6$adapted(Logger.scala:42)
	at scala.Option.foreach(Option.scala:274)
	at scribe.Logger.$anonfun$log$3(Logger.scala:42)
	at scribe.Logger.$anonfun$log$3$adapted(Logger.scala:40)
	at scala.Option.foreach(Option.scala:274)
	at scribe.Logger.log(Logger.scala:40)
	at scribe.package$.log(package.scala:10)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$withTimer$1(MetalsLanguageServer.scala:1209)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	... 5 more
```

Steps to reproduce:

1. `git clone https://github.com/hugo-vrijswijk/stryker4s && git checkout vscode-devcontainer`
2. Open the folder in VS Code Insiders with the extensions from above article installed
3. Click 'Reopen in container'
4. Wait for a while, then 'Internal error' notification shows up
5. Observe logs in Metals output

**Expected behavior**

Metals is installed in the container and runs amazingly as usual

**Installation:**

- Operating system: Windows
- VSCode version: 1.34.0-insider
- VSCode extension version: 1.3.2
- Metals version: 0.5.1

**Comment by gabro** [comment]
Hi @hugo-vrijswijk, thanks for reporting. I'm pretty excited about that feature as well!

I've just tried to reproduce the steps above and I got it working:

![2019-05-04 11 08 32](https://user-images.githubusercontent.com/691940/57176820-28fa0a80-6e5d-11e9-8b7d-370e80e3f0ac.gif)

(notice the dev container badge on the bottom left)

I did hit on a strange error the first time I've tried (Metals not being able to connect to the BSP server), but I had already started to import the build by accident, and then killed the process, so probably something got mixed up.

Then I've deleted the `.metals` and `.bloop` directories entirely, tried to run it again inside the container and it worked at the first try :O

**Comment by hugo-vrijswijk** [comment]
Hmm, strange. The metals.log file showed up on vs code and on `ls` but I couldn't delete it (said the file didn't exist). I'll see if I can try again on a different computer. I also noticed you're running on macOS, while I had the problem on Windows. Maybe that also had something to do with it

**Comment by gabro** [comment]
Mmm, Docker for Windows may be playing some tricks with volumes. Have you tried disabling the experimental flag of Docker for Win? (for some reason it's usually enabled by default)

**Comment by hugo-vrijswijk** [comment]
The issue definitely seems to be Windows related. I just tried on a Linux host, and it works perfectly. 

> Have you tried disabling the experimental flag of Docker for Win?

It was disabled for me, but even with it enabled I had the same issue.

Other file operations (creating new files, editing, removing) work just fine inside the container

**Comment by inkytonik** [comment]
I've had a similar problem on Mac OS X. I *think* the issue was that Metals was running on the OS X side when I opened the dev container. The Metals instance that tries to start up in the container is sharing the .metals/.bloop folders with the one on the OS X side. I presume that this is not supported so something gets clobbered. I was able to get things going properly by removing the .metals and .bloop folders and starting again but making sure not to import the build on the OS X side.

**Comment by vincenzobaz** [comment]
I got it working!
I used the very handy image https://github.com/hseeberger/scala-sbt
with a simple `Dockerfile`:
```
FROM hseeberger/scala-sbt:8u181_2.12.8_1.2.8
USER sbtuser
````
and the `devcontainer.json`:
```
{
	"name": "sbt",
	"dockerFile": "Dockerfile",
	"extensions": [
		"scalameta.metals",
		"scala-lang.scala"
	]
}
```

**Comment by olafurpg** [comment]
Please reopen if you are able to reproduce with the latest remote development and latest Metals version
