### ISSUE TITLE
Mainclass not found after updating extension from 1.23.0 to 1.24.0

### ISSUE THREAD

**Issue by Thejipppp** [scalameta/metals-vscode#1409]
**Describe the bug**

After updating the Scala (metals) extension in VSCode on 2023/07/20, the mainclass is not found anymore and thus cannot run anymore in a project that uses a workspace. The workspace contains multiple sbt projects.
In a project without workspace, everything still works.
Opening only the project with the mainclass and running it, also still works, but then of course you don't see the subprojects anymore in the editor.

**To Reproduce** Steps to reproduce the behavior:

1. Have two sbt projects, the one with the mainclass depending on the other
2. Add a .vscode/myWorkspace.code-workspace file to the project with the mainclass
3. Link to the two projects in there `"folders": [
		{
			"path": ".."
		},
		{
			"path": "../../my-second-project"
		}
	],`
4. The mainclass is not found anymore when running the project in VSCode.

**Expected behavior**

The project runs as expected

**Installation:**

- Operating system: Windows
- VSCode version: 1.80.1
- VSCode extension version: 1.24.0
- Metals version: 1.0.0

**Search terms**

Visual Studio Code, Breaking Change, Update, Latest Version,

**Comment by Thejipppp** [comment]
I will finish the project I'm now working on (in 1.23.0) and then try to make a reproducer! Thanks for the quick answer!

**Comment by Thejipppp** [comment]
It will probably not win a beauty contest, but I wrote a reproducer [here](https://github.com/Thejipppp/vscode-metals-folder-issue-reproducer/tree/master/head-project).

It basically contains two projects.
- SubProject containing a case object "Example"
- MainProject containing the main method that prints the example case object.

When you run the Main method via the editor, it works.
When you however try to run the provided launch.json, you get
`[Error - 2:41:13 PM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.ClassNotFoundException: com.thejipppp.example.metals.main.Main
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.thejipppp.example.metals.main.Main
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.$anonfun$findClassAndBuildTarget$1(BuildTargetClassesFinder.scala:112)
	at scala.Option.fold(Option.scala:263)
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.findClassAndBuildTarget(BuildTargetClassesFinder.scala:113)
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.findMainClassAndItsBuildTarget(BuildTargetClassesFinder.scala:36)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$findMainClassAndItsBuildTarget$1(DebugProvider.scala:530)
	at scala.meta.internal.metals.debug.DebugProvider$$anonfun$withRebuildRetry$1.$anonfun$applyOrElse$6(DebugProvider.scala:809)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	... 3 more`

Does this give you enough information to troubleshoot the problem?
