### ISSUE TITLE
Fails to download on Windows with output "Error creating cache directory...Caused by: java.nio.file.AccessDeniedException: C:\Program Files\Microsoft VS Code\null"

### ISSUE THREAD

**Issue by jarhart** [scalameta/metals-vscode#1448]
**Describe the bug**

Fails with message:

```
Failed to download Metals, make sure you have an internet connection, the Metals version '1.2.0' is correct and the Java Home 
'C:\Program Files\Java\jdk-17' is valid. You can configure the Metals version and Java Home in the settings.See 
https://scalameta.org/metals/docs/editors/vscode/#http-proxy for instructions if you are using an HTTP proxy.
```

**Output**

```
Java home: C:\Program Files\Java\jdk-17
Metals version: 1.2.0
Exception in thread "main" java.lang.RuntimeException: Error creating cache directory
	at coursier.bootstrap.launcher.c.a(Unknown Source)
	at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
Caused by: java.nio.file.AccessDeniedException: C:\Program Files\Microsoft VS Code\null
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:521)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
	at java.base/java.nio.file.Files.createDirectories(Files.java:793)
	at coursier.bootstrap.launcher.u.a(Unknown Source)
	at coursier.bootstrap.launcher.p.a(Unknown Source)
	at coursier.bootstrap.launcher.o.a(Unknown Source)
	... 2 more
```

**Installation:**

- Operating system: Windows 11
- VSCode version: 1.8.5
- VSCode extension version: v1.27.0
- Metals version: 1.2.0

**Additional context**

- Scala version 3.3.1
- Sbt version 1.9.8

**Comment by tgodzik** [comment]
Thanks for reporting! Looks like an issue we already solved for other things in Metals, but this time it's an issue with coursier. I will try and update coursier binary, this might be fixed there, though not 100% sure about it.

**Comment by tgodzik** [comment]
A workaround could be installing coursier manually locally, we should be able to pick it up and not run the boostrap.

https://get-coursier.io/docs/cli-installation#windows

**Comment by tgodzik** [comment]
https://github.com/scalameta/metals-vscode/issues/1450 <- should solve it, we want to work on it sometime soon

**Comment by jarhart** [comment]
> A workaround could be installing coursier manually locally, we should be able to pick it up and not run the boostrap.
> 
> https://get-coursier.io/docs/cli-installation#windows

That worked great! Thank you!

**Comment by tgodzik** [comment]
Good to hear that, since this will be solved by https://github.com/scalameta/metals-vscode/issues/1450 I will close this one.
