### ISSUE TITLE
Timeout waiting for 'build/initialize' response

### ISSUE THREAD

**Issue by ykafia** [scalameta/metals-vscode#181]
I'm having a hard time setting up metals and i can't really understand why.

I did a simple build.sbt

```sbt
name := "scalaproject"
version := "7"
scalaVersion := "2.13.1"
```

Then I import the changes and the logs display : 

```powershell
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 31513'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Waiting for a connection at 127.0.0.1:31513...
The server is listening for incoming connections at tcp://127.0.0.1:31513...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
ERROR Timeout waiting for 'build/initialize' response
ERROR Failed to connect with build server, no functionality will work.
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at scala.meta.internal.metals.BuildServerConnection$.initialize(BuildServerConnection.scala:259)
	at scala.meta.internal.metals.BuildServerConnection$.$anonfun$fromSockets$1(BuildServerConnection.scala:203)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by tgodzik** [comment]
@ykafia thanks for reporting, is there anything else in the logs? Are you using a proxy or custom repositories? Is bloop server running in the background?

**Comment by ykafia** [comment]
I am behind a proxy. I've set up the proxy in the .jvmopts and it seems to work quite well. Everything that needed to be downloaded was downloaded.
I'm not using a custom repository either.

How should i check if there's a bloop server is running in the background?
This is my first time using sbt and metals if anything.

This comes up after the error message : 

```powershell 
INFO  no build target: using presentation compiler with only scala-library
WARN  no build target for: G:\ScalaProj\scala2\src\main\scala\App.scala
WARN  Stopped configuration of SemanticDB in Scala 2.13.1 projects: Error downloading org.scalameta:semanticdb-scalac_2.13.1:4.3.0
  not found: C:\Users\ykafia\.ivy2\local\org.scalameta\semanticdb-scalac_2.13.1\4.3.0\ivys\ivy.xml
  download error: Caught java.net.ConnectException: Connection timed out: connect (Connection timed out: connect) while downloading https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.1/4.3.0/semanticdb-scalac_2.13.1-4.3.0.pom
  download error: Caught java.net.ConnectException: Connection timed out: connect (Connection timed out: connect) while downloading https://dl.bintray.com/scalacenter/releases/org/scalameta/semanticdb-scalac_2.13.1/4.3.0/semanticdb-scalac_2.13.1-4.3.0.pom

```

**Comment by tgodzik** [comment]
Ok, currently there is an issue when trying to resolve semanticDB - we don't add the right proxy flags. 
Could you copy `.jvmopts` to `<user_home>/.bloop` - this is a current workaround

Closing this in favour of https://github.com/scalameta/metals/issues/1315
