### ISSUE TITLE
semanticdb-scalac.jar not found

### ISSUE THREAD

**Issue by kogiokka** [scalameta/metals-vscode#231]
**Describe the bug**
All the IDE features don't work (syntax checking, run/debug tag...)

**To Reproduce** Steps to reproduce the behavior:
1. `sbt new scala/scala-seed.g8` to generate a project.
2. Open the project root folder in VSCode.
3. Execute `Import Build`
4. No error notifications. The error messages are in `metals.log`, as follows:
```
INFO  started: Metals version 0.8.1 in workspace '/home/luis/Mapt/Scala/learn-scala-01'
INFO  time: initialize in 1.31s
WARN  no build target for: /home/luis/Mapt/Scala/learn-scala-01/src/main/scala/example/Hello.scala
INFO  running '/home/luis/.sdkman/candidates/java/current/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /tmp/metals12922832343987615947/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'
INFO  [info] Loading settings for project learn-scala-01-build from metals.sbt ...
INFO  [info] Loading project definition from /home/luis/Mapt/Scala/learn-scala-01/project
INFO  [info] Loading settings for project root from build.sbt ...
INFO  [info] Set current project to learn-scala-01 (in build file:/home/luis/Mapt/Scala/learn-scala-01/)
INFO  [success] Generated .bloop/root.json
INFO  [success] Generated .bloop/root-test.json
INFO  [success] Total time: 1 s, completed Mar 8, 2020, 12:04:01 PM
INFO  build tool exit: 0
INFO  time: ran 'sbt bloopInstall' in 32s
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /tmp/bsp-launcher16141528339525151669/bsp.socket'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Waiting for a connection at local:///tmp/bsp-launcher16141528339525151669/bsp.socket...
The server is listening for incoming connections at local:///tmp/bsp-launcher16141528339525151669/bsp.socket...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/luis/.cache/metals/bsp.trace.json
INFO  time: connected to build server in 0.27s
INFO  Connected to Build server v1.4.0-RC1-69-693de22a
INFO  time: indexed workspace in 2.65s
INFO  Deduplicating compilation of root from bsp client 'Metals 0.8.1' (since 2m 33.773s)
ERROR /home/luis/.cache/bloop/semanticdb/org.scalameta.semanticdb-scalac_2.13.1.4.3.0/semanticdb-scalac_2.13.1-4.3.0.jar
java.nio.file.FileSystemNotFoundException: /home/luis/.cache/bloop/semanticdb/org.scalameta.semanticdb-scalac_2.13.1.4.3.0/semanticdb-scalac_2.13.1-4.3.0.jar
	at jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:116)
	at jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:109)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:337)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:286)
	at scala.meta.internal.io.PlatformFileIO$.newFileSystem(PlatformFileIO.scala:103)
	at scala.meta.internal.io.PlatformFileIO$.newJarFileSystem(PlatformFileIO.scala:99)
	at scala.meta.internal.io.PlatformFileIO$.withJarFileSystem(PlatformFileIO.scala:76)
	at scala.meta.internal.io.FileIO$.withJarFileSystem(FileIO.scala:43)
	at scala.meta.internal.metals.CompilerPlugins.liftedTree1$1(CompilerPlugins.scala:63)
	at scala.meta.internal.metals.CompilerPlugins.isSupportedPlugin(CompilerPlugins.scala:62)
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$filterSupportedOptions$2(CompilerPlugins.scala:44)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:897)
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$filterSupportedOptions$1(CompilerPlugins.scala:44)
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$filterSupportedOptions$1$adapted(CompilerPlugins.scala:41)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:256)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:255)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:249)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:347)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:347)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
	at scala.meta.internal.metals.CompilerPlugins.filterSupportedOptions(CompilerPlugins.scala:41)
	at scala.meta.internal.metals.Compilers.newCompiler(Compilers.scala:297)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$9(Compilers.scala:248)
	at scala.meta.internal.metals.StatusBar.trackBlockingTask(StatusBar.scala:45)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$8(Compilers.scala:248)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2682)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$7(Compilers.scala:244)
	at scala.Option.map(Option.scala:230)
	at scala.meta.internal.metals.Compilers.$anonfun$loadCompiler$6(Compilers.scala:241)
	at scala.Option$WithFilter.flatMap(Option.scala:271)
	at scala.meta.internal.metals.Compilers.loadCompiler(Compilers.scala:233)
	at scala.meta.internal.metals.Compilers.$anonfun$load$3(Compilers.scala:97)
	at scala.meta.internal.metals.Compilers.$anonfun$load$3$adapted(Compilers.scala:96)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.meta.internal.metals.Compilers.$anonfun$load$1(Compilers.scala:96)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)

Exception in thread "pool-4-thread-1" java.lang.NoClassDefFoundError: scala/meta/inputs/Input
	at scala.meta.internal.pc.ScalaPresentationCompiler.newCompiler(ScalaPresentationCompiler.scala:194)
	at scala.meta.internal.pc.ScalaPresentationCompiler.$anonfun$access$1(ScalaPresentationCompiler.scala:61)
	at scala.meta.internal.pc.CompilerAccess.loadCompiler(CompilerAccess.scala:36)
	at scala.meta.internal.pc.CompilerAccess.withSharedCompiler(CompilerAccess.scala:120)
	at scala.meta.internal.pc.CompilerAccess.$anonfun$withNonInterruptableCompiler$1(CompilerAccess.scala:110)
	at scala.meta.internal.pc.CompilerAccess.$anonfun$onCompilerJobQueue$1(CompilerAccess.scala:198)
	at scala.meta.internal.pc.CompilerJobQueue$Job.run(CompilerJobQueue.scala:101)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: scala.meta.inputs.Input
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 10 more
WARN  Disconnecting from deduplication of ongoing compilation for 'root'
No progress update for 30 seconds caused bloop to cancel compilation and schedule a new compile.
```

                  

**Expected behavior**
The IDE features should work after `Import Build` command.

**Screenshots**

**Installation:**

- Operating system: Linux (Fedora)
- VSCode version: 1.42.1
- VSCode extension version: 1.8.0
- Metals version: 0.8.1

**Additional context**
Both Java and sbt are installed through sdkman. `Metal: Sbt Script` is left blank.
JDK version: `OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)`

The extension worked once perfectly, but I couldn't reproduce it again. There was another problem before this bug report. So I had remove `.cache/` and `.vscode/` folders and reinstall VSCode to get a clean environment.

**Search terms**

**Comment by tgodzik** [comment]
Hey, thanks for reporting. It looks like the issues we've been having with xss:

scalameta/metals#1347

and

scalacenter/bloop#1168

Updating ~/.bloop/.jvmopts to use higher xss setting can help. This will be the default in later versions of Bloop.

I don't think it's a problem with fastparse, even if Metals uses it, the compilation classpath is totally separate from Metals one.

Let me know if this helps!

**Comment by kogiokka** [comment]
`.jvmopts` works by putting it under the root folder of the project (the same level as `build.sbt`).

 After some tests I've get more details about this problem:

**Reproduce steps**
1. `rm ~/.cache/coursier` (The action trigger the bug.)
2. Create a seed project with `sbt new scala/scala-seed.g8 --name=test`
3. Open the project root folder in VSCode.
4. Execute `Import Build`

**Solution**
Set `-Xss8m` in `.jvmopts` inside the root folder.

It turns out that there is still a running java process even the editor has been closed (with or without this bug). I think it is a bug, too?

**Comment by tgodzik** [comment]
That's the Bloop build server server, it's not turned off automatically, since the single instance will work for many workspaces. We should be able to do that automatically under an option, but that will need to be discussed in a separate feature. This will not be useful for anyone working daily with Scala.

**Comment by tgodzik** [comment]
Glad it help! Closing this for now, we can follow up with the feature request for auto-closing Bloop in scalameta/metals-feature-requests repo.
