### ISSUE TITLE
Failed to debug a scala maven project

### ISSUE THREAD

**Issue by Khalid-Nowaf** [scalameta/metals-vscode#319]
**Describe the bug**
Running the debugger in a scala maven project produce the following error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Predef$
	at com.test.App$.main(App.scala:11)
	at com.test.App.main(App.scala)
Caused by: java.lang.ClassNotFoundException: scala.Predef$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

which indicate that all the dependencies, including scala are not included.

Also, the following command runs with no issues in the maven project
```
mvn compile
mvn test
mvn package
```
**To Reproduce** Steps to reproduce the behavior:

1. generate new mavan scala project ` mvn archetype:generate`
2. enter the following to filler the selection `net.alchim31.maven:scala-archetype-simple`
3. enter '1'
4. follow the rest instructions to generate the project
5. once the project created, open it with vscode and try to run the debugger 

**Expected behavior**

Scala maven projects should be runable and debugable as scala sbt project

**Comment by tgodzik** [comment]
Thanks for reporting! This is an issue with how the Bloop config is currently generated. In the platform section it adds `classpath: []`, which means it will not have scala library on the classpath. We will need to investigate what is exactly an issue in Bloop.
