### ISSUE TITLE
Broken highlighitng and reference search

### ISSUE THREAD

**Issue by putnam120** [scalameta/metals-vscode#373]
**Describe the bug**
When enabled, the extension disables the ability to highlight all methods and variable occurrences when clicking on a one occurrence. Similarly I'm unable to view references to selected methods, even when the only references are in the same file.

**To Reproduce**
1. Write a method and code that calls that method.
2. Click on the method name.
3. Right click and select "Go to References"
4. After step 2 you should see that neither the method or where it's used are highlighted. Then after step 3 observe a "No references found" message.

**Expected behavior**
After step 2 from the steps to reproduce both the method name and its reference should be highlighted.
After step 3 the location where the method is used should be found.

**Screenshots**
Example of when extension is enabled and use clicks on the method (pathToMapUpdate in this case).

<img width="504" alt="Screen Shot 2020-08-03 at 8 18 11 PM" src="https://user-images.githubusercontent.com/9420163/89250085-ca27c180-d5c8-11ea-8f32-8a1f800f3ffe.png">

Example of expected behavior (obtained when extension is disabled).
<img width="414" alt="Screen Shot 2020-08-03 at 8 20 52 PM" src="https://user-images.githubusercontent.com/9420163/89250181-065b2200-d5c9-11ea-86f1-6f146371be71.png">

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code v1.47.3
- Metals version: v1.9.2

**Search terms**

highlighting, reference search

**Comment by tgodzik** [comment]
Thanks for reporting! Metals uses compiled artifacts to find references and highlight occurrences, does the code compile? Is there anything in `.metals/metals.log` that would point to an issue?

When extension is disabled VS Code just falls back to text highlighting.

**Comment by putnam120** [comment]
Yes the code compiles, and even after compiling my code I still don't see the highlighting. As for the `.metals/metals.log` file the only things that look out of place are as follow

`Jul 31, 2020 10:31:18 AM scala.meta.internal.pc.completions.Completions completionPosition
SEVERE: null
java.lang.NullPointerException
	at scala.meta.internal.pc.completions.OverrideCompletions$OverrideCompletion.<init>(OverrideCompletions.scala:46)
	at scala.meta.internal.pc.completions.Completions.completionPositionUnsafe(Completions.scala:504)
	at scala.meta.internal.pc.completions.Completions.completionPositionUnsafe$(Completions.scala:413)
	at scala.meta.internal.pc.MetalsGlobal.completionPositionUnsafe(MetalsGlobal.scala:29)
	at scala.meta.internal.pc.completions.Completions.completionPosition(Completions.scala:405)
	at scala.meta.internal.pc.completions.Completions.completionPosition$(Completions.scala:390)
	at scala.meta.internal.pc.MetalsGlobal.completionPosition(MetalsGlobal.scala:29)
	at scala.meta.internal.pc.CompletionProvider.safeCompletionsAt(CompletionProvider.scala:444)
	at scala.meta.internal.pc.CompletionProvider.completions(CompletionProvider.scala:57)
	at scala.meta.internal.pc.ScalaPresentationCompiler.$anonfun$complete$1(ScalaPresentationCompiler.scala:182)
	at scala.meta.internal.pc.CompilerAccess.withSharedCompiler(CompilerAccess.scala:137)
	at scala.meta.internal.pc.CompilerAccess.$anonfun$withInterruptableCompiler$1(CompilerAccess.scala:87)
	at scala.meta.internal.pc.CompilerAccess.$anonfun$onCompilerJobQueue$1(CompilerAccess.scala:197)
	at scala.meta.internal.pc.CompilerJobQueue$Job.run(CompilerJobQueue.scala:103)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

and 

`2020.07.31 18:30:22 INFO  started: Metals version 0.9.2 in workspace '<path to project directory>' for client vscode.`
`java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@273d37d rejected from java.util.concurrent.ThreadPoolExecutor@1811519c[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by tgodzik** [comment]
Is there nothing about a missing target or non existing semanticdb files? That should pop up in the situations like this.

Do you maybe have a small repro somewhere? Where are you source files located (we need it to be under `/src/main/scala`) and what are the names?

**Comment by putnam120** [comment]
No I'm not seeing any messages about missing targets or anything. All my code is under `/src/main/scala`.

I just created a new project and it seems to be working there so I'm guessing there's something non metals related that's wrong in this project.

**Comment by tgodzik** [comment]
Maybe the extension didn't start properly or the build import failed? Could you try running "Build import" via commands or in the Metals tree view on the left? You could also try running the doctor (should be somewhere next to build impoty) to see if there is any info there.

**Comment by putnam120** [comment]
Not sure what's changed but I no longer see this issue. Going to close.
