### ISSUE TITLE
Publihsing to open-vsx fails: Cannot find module 'didyoumean'

### ISSUE THREAD

**Issue by sideeffffect** [scalameta/metals-vscode#423]
The `Publish on Open VSX` step wails with

```
$ ovsx publish --pat *** ./metals-1.9.4.vsix
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'didyoumean'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/runner/work/metals-vscode/metals-vscode/node_modules/ovsx/lib/main.js:13:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
```

https://github.com/scalameta/metals-vscode/runs/1146151220?check_suite_focus=true#step:15:13

**Comment by tgodzik** [comment]
@sideeffffect It does, but it masks the real error. I published last releases manually and probably will need to do it again enxt time, but hopefully we'll get proper error to debug it.

**Comment by tgodzik** [comment]
But thanks for reporting!

**Comment by tgodzik** [comment]
Last release worked! :tada:
