### ISSUE TITLE
Diagnostics missing and vscode-languageclient logging error

### ISSUE THREAD

**Issue by blikkiee** [scalameta/metals-vscode#639]
Diagnostics are missing. When I make a typo to trigger an compilation error, no diagnostics are shown.

The logs of metals seem ok. Metals correctly diagnoses the compilation error.
However, no visual feedback of the compilation error is shown in the editor. Also the log of the extension host report an error in the vscode-language client:

```
[2021-07-30 22:35:42.391] [exthost] [error] [scalameta.metals] provider FAILED
[2021-07-30 22:35:42.391] [exthost] [error] Canceled: Canceled
	at LanguageClient.makeCancelError (/home/user/.vscode/extensions/scalameta.metals-1.10.8/node_modules/vscode-languageclient/lib/common/client.js:2666:24)
	at LanguageClient.handleFailedRequest (/home/user/.vscode/extensions/scalameta.metals-1.10.8/node_modules/vscode-languageclient/lib/common/client.js:2656:28)
	at /home/user/.vscode/extensions/scalameta.metals-1.10.8/node_modules/vscode-languageclient/lib/common/client.js:908:39
```

**Installation:**

- Operating system: Ubuntu 20.04.2 LTS
- VSCode version: 1.58.2
- VSCode extension version: 1.10.8
- Metals version: 0.10.5

**Comment by tgodzik** [comment]
Thanks for reporting! This looks like if the Metals server hasn't successfully started? What is the java version you are using and could you add the full logs you find in the Output (Metals) ? There might be sometimes more info in `.metals/metals.log`

**Comment by blikkiee** [comment]
the java version that I use is 
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

I tried to start up the smallest project that I use: the log file attached reflects (1) opening a project, (2) importing the build (which triggers the actual sbt compile), and (3) making a typo to trigger diagnostics.

[metals.log](https://github.com/scalameta/metals-vscode/files/6923333/metals.log)

Also note that when I use the hello world example the diagnostics actually do work... Not sure to what kind of project settings this error could be related.

**Comment by tgodzik** [comment]
Based on your logs it seems that the compiler is crashing which is why the diagnostics are not being published.

```
[0m2021.08.03 12:10:40 ERROR Unexpected error when compiling zd-crypto: 'assertion failed: 
  new JcaPEMKeyConverter()
     while compiling: /home/user/Documents/zd-crypto/src/main/scala/nl/company/crypto/CryptoUtils.scala
```
This looks suspicious, any idea where it might be coming from?

**Comment by blikkiee** [comment]
well that timestamp is the moment that I purposefully made a typo and saved the file to trigger the diagnostics. But somehow that crashes the compiler... Not sure why it would crash though

**Comment by tgodzik** [comment]
There is a weird assertion there probably, maybe something that needs a configuration from the resources? And that might not be handled properly? I would love to try to fix it with a small reproduction is possible.

Moving it to the main repo as it's not just VS Code
