### ISSUE TITLE
Debugging a Play Framework application

### ISSUE THREAD

**Issue by chausner-audeering** [scalameta/metals-vscode#906]
**Describe the bug**

I am attempting to debug a Play Framework application. I am able to successfully import the project and get code completion but I haven't figured out how to get the debugger integration working.

**To Reproduce** Steps to reproduce the behavior:

I created a new launch configuration:
```json
{
    "type": "scala",
    "request": "launch",
    "name": "Launch",
    "mainClass": "play.core.server.ProdServerStart",
    "args": [],
    "jvmOptions": [],
    "env": {}
}
```
I am not sure if the main class is correct, I found it in the startup scripts generated by the Play sbt plugin:
```bash
declare -a app_mainclass=(play.core.server.ProdServerStart)
```

When attemping to run this configuration, I get the error message "Internal error." and the following is logged to the output of the Metals extension:
```
[Error - 4:22:38 PM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.nio.file.ProviderMismatchException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:42)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.file.ProviderMismatchException
	at java.base/sun.nio.fs.UnixPath.toUnixPath(UnixPath.java:198)
	at java.base/sun.nio.fs.UnixPath.relativize(UnixPath.java:423)
	at java.base/sun.nio.fs.UnixPath.relativize(UnixPath.java:43)
	at scala.meta.io.AbsolutePath.toRelative(AbsolutePath.scala:40)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionAbsolutePathBuffers.toRelativeInside(MetalsEnrichments.scala:308)
	at scala.meta.internal.metals.BuildTargets.inferBuildTarget(BuildTargets.scala:367)
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.findTarget$1(BuildTargetClassesFinder.scala:72)
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.$anonfun$revertToDependencies$5(BuildTargetClassesFinder.scala:82)
	at scala.Option.orElse(Option.scala:447)
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.$anonfun$revertToDependencies$4(BuildTargetClassesFinder.scala:82)
	at scala.Option.flatMap(Option.scala:271)
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.$anonfun$revertToDependencies$3(BuildTargetClassesFinder.scala:81)
	at scala.collection.immutable.List.flatMap(List.scala:366)
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.scala$meta$internal$metals$debug$BuildTargetClassesFinder$$revertToDependencies(BuildTargetClassesFinder.scala:77)
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder$$anonfun$findMainClassAndItsBuildTarget$4.applyOrElse(BuildTargetClassesFinder.scala:43)
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder$$anonfun$findMainClassAndItsBuildTarget$4.applyOrElse(BuildTargetClassesFinder.scala:37)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at scala.util.Failure.recoverWith(Try.scala:236)
	at scala.meta.internal.metals.debug.BuildTargetClassesFinder.findMainClassAndItsBuildTarget(BuildTargetClassesFinder.scala:37)
	at scala.meta.internal.metals.debug.DebugProvider.$anonfun$resolveMainClassParams$1(DebugProvider.scala:423)
	at scala.meta.internal.metals.debug.DebugProvider.withRebuildRetry(DebugProvider.scala:639)
	at scala.meta.internal.metals.debug.DebugProvider.resolveMainClassParams(DebugProvider.scala:419)
	at scala.meta.internal.metals.MetalsLanguageServer.executeCommand(MetalsLanguageServer.scala:1769)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
```

**Expected behavior**

The Play Framework application should start in debug mode, as if running `sbt run` and the debugger should be attached.

**Installation:**

- Operating system: Ubuntu 20.04
- VSCode version: 1.65.0
- VSCode extension version: 1.12.0
- Metals version (found in VSCode settings, under `metals.serverVersion`): 0.11.1

**Additional context**

**Search terms**

**Comment by kpodsiad** [comment]
Could you take a look at https://github.com/scalameta/metals/issues/3575#issuecomment-1024493049? It seems you lack `buildTarget` - you can use Metals doctor to obtain the build target name.

**Comment by tgodzik** [comment]
I was thinking that we could show quickpick in case that we are not able to determine the actual target. We could even update the configuration at that point automatically.

**Comment by chausner-audeering** [comment]
Thanks for that hint! Indeed, by adding `"buildTarget": "root"`, it starts the application and attaches. What I found out so far:
* The application needs to have been built manually beforehand, otherwise I still get the same bad error message ("Internal error.")
* Without setting proper JVM arguments, the Play app starts but some parts don't work correctly. For example, static content is not served correctly. I ran `sbt runProd` and looked up the JVM arguments that it uses, and set them in the `jvmOptions` attribute in the launch configuration:
  ```json
    "jvmOptions": [
      "-Dfile.encoding=UTF-8",
      "-Duser.dir=/home/../target/universal/stage",
      "-Dhttp.port=9000",
      "-cp", "/home/../target/universal/stage/lib/../conf/:..." # a very long argument listing all JAR dependencies
  ],
  ```
  That already fixes some of the problems but I am still seeing some static content not served correctly. Will need to investigate further.

**Comment by tgodzik** [comment]
Classpath should be set up correctly, so ideally no reason to have `-cp` option. If you want to debug the application and alternative would be to attach to a existing server started by sbt. There is a separate attach configuration for that.
